### ISSUE TITLE
How to auto recorder call when incoming & outcoming call?

### ISSUE THREAD

**Issue by vanloc0301** [TayfunCesur/RecordPhoneCalls#2]
I don't know how to auto recorder call.

You application must open app and click to button to start record.

**Comment by TayfunCesur** [comment]
Hey. This app records automatically. That start button starts **services** not the record. Just start first time for the start listener services that's enought. You don't have to start anymore.

**Comment by vanloc0301** [comment]
Thanks for your reply.
