### ISSUE TITLE
How to fix application throws exception: "Unfortunately, Record Calls has stopped"

### ISSUE THREAD

**Issue by vanloc0301** [TayfunCesur/RecordPhoneCalls#3]
And I have problem like:
I installed your provider sample .apk file, it works perfectly.
When I uninstall and remove folder: `GorusmeKayitlari` in memory.

But when I fork your repository.
I'm set-up step by step like:
1. Import your project to the Android studio to create grade build system.
2. Download Google APIs from SDK manager and swap to JDK 1.7.
3. Add dependency library: `com.android.support:support-v4:24.0.0-alpha1`.

Yup, that work.

Run this app and show this pop-up:
`Unfortunately, Record Calls has stopped.`

I'm started debug, and issues like:
1. Application start at line:
                 `ArrayList<String> files = GetFiles(CallHelper.PATH);`
                  But CallHelper.PATH = null.  And I change to `Environment.getDataDirectory()`. My device has External Storage. This variable still is null.
2. In method `GetFile()` of class `Records`. 
                  `files = file.listFiles();` is null. So when to check this in `if statement` it occurs exception. 
                   I think this is main reason application is stopped working.

How to fix this exception? Thank you very much.

**Comment by TayfunCesur** [comment]
Upps sorry my bad. You are getting nullreferences which is exactly normal. Because can't create File object from your new path and returns null. So, can't get lenght of null , it throws null references exception. I fixed this by adding simple if statement to check return value is not null. Check this reporsitory now and it will be handled. 

Changes are Line 55 in Record.class and Line 27 in ListViewAdapter. 

Cheers!

**Comment by vanloc0301** [comment]
@TayfunCesur thanks. I checked your code updated. It's working.

But I have problem like:
1. I open the app and click the button to record.
2. Start call number, when end call application continues show popup:
   `Unfortunately, Record Calls has stopped.`

I tried to debug: but can get any exception. Can you try to debug app? It will show exception.

This application auto start when an incoming & outcoming call, don't need click button circle and updated list audio record real-time when call end.

How to edit your code to do like this? I think to add `Button_click` event into start app.

**Comment by TayfunCesur** [comment]
I have many users for this app and I have never get an issue like this. This is probably related with your device. What is your device ?

**Comment by vanloc0301** [comment]
I test in Xiaomi Red mi note 2 with android 5.0.2, HTC desire 820s with android 4.4.4 and Samsung Galaxy S6 with android 6.0.

Before you edit code, I can record on any device and show list record.
After update code, I can't record, when to call to any number, it required `Allow record for Call Records` and I press `Allow`, after end the call it shows this exception.

I think you update code have issues. Can you check again?

Current, I have device Red mi note 2 (No sdcard, it's bug?), HTC desire 820s(with sdcard) but I don't have phone at this time, so I can't test.

Thanks.

**Comment by vanloc0301** [comment]
@TayfunCesur  Can you check and update code? Please!

**Comment by TayfunCesur** [comment]
I can't change my code according to your desires. If you want auto-update list when calls are finish, you must do it yourself.

And after some research, I get that information which is android 6.0 don't let us listen VOICE_CALL. You must change audiosource like below
recorder.setAudioSource(MediaRecorder.AudioSource.MIC);

and see this post [Android Media Recording: java.lang.RuntimeException: start failed](http://stackoverflow.com/questions/23465821/android-media-recording-java-lang-runtimeexception-start-failed)
please make your test in device which has sdCard!

**Comment by vanloc0301** [comment]
@TayfunCesur  I checked Android 6.0 can't record call. But I test your code in Android 4.4.4 and Android 5.0.2 and result is application throw exception: 'Unfortunately, Record Calls has stopped.'. So, I think your code when update have issues.
Pls check this responsitory source in your device.
I think your have bug like me.
Because I tested in 2 device run 2 android version different.
Thanks pro. You don't need change code like I required (auto start,....).

**Comment by TayfunCesur** [comment]
in android 6.0 it does not works because there is needed runtime permissions. And I did not design this app for 6.0. See  [Runtime Permissions](http://developer.android.com/training/permissions/requesting.html).

I tested my genymotien emulators. So it works like charm in nexus series but some samsung series I get an exception which is I already know. Media recorder stop failed exception. And I have **already** opened an issue see [Issue 1](https://github.com/TayfunCesur/RecordPhoneCalls/issues/1). Still searching, not found.

**Comment by vanloc0301** [comment]
@TayfunCesur   I know it working in android 6.0 so I only need it working in android 5.0.2 lollipop . 
You write any samsung model have exception. But I check in Xiaomi and HTC phone . It not working. 
Have you real device? I don't test in Genymotion because I don't have premium account. If you using free version of genymotion it will block advance api include : Call, gps,..
In short , it can't run in all device I tested include : Xiaomi, Htc with Android version small than 5.0.2
